[2025-05-02T18:24:57.952+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T18:24:57.957+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T18:24:57.958+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-02T18:24:57.967+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): normalize_data> on 2025-05-01 00:00:00+00:00
[2025-05-02T18:24:57.972+0000] {standard_task_runner.py:60} INFO - Started process 1933 to run task
[2025-05-02T18:24:57.974+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'normalize_data', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmpweryqcki']
[2025-05-02T18:24:57.976+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask normalize_data
[2025-05-02T18:24:58.017+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-01T00:00:00+00:00 [running]> on host 82b06739c44f
[2025-05-02T18:24:58.073+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='normalize_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-02T18:24:58.075+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvfc6akuie --system-site-packages --python=python
[2025-05-02T18:24:58.081+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T18:24:58.651+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 300ms
[2025-05-02T18:24:58.652+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvfc6akuie, clear=False, no_vcs_ignore=False, global=True)
[2025-05-02T18:24:58.652+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmpia2izd1o)
[2025-05-02T18:24:58.653+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-02T18:24:58.653+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-02T18:24:58.674+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvfc6akuie/bin/pip install -r /tmp/venvfc6akuie/requirements.txt
[2025-05-02T18:24:58.680+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T18:24:59.340+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-02T18:24:59.541+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venvfc6akuie/requirements.txt (line 1))
[2025-05-02T18:24:59.579+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-02T18:24:59.582+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvfc6akuie/requirements.txt (line 2)) (1.37.38)
[2025-05-02T18:24:59.584+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvfc6akuie/requirements.txt (line 3)) (2.17.2)
[2025-05-02T18:24:59.584+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvfc6akuie/requirements.txt (line 4)) (1.3.2)
[2025-05-02T18:24:59.616+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvfc6akuie/requirements.txt (line 1)) (1.37.38)
[2025-05-02T18:24:59.618+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvfc6akuie/requirements.txt (line 1)) (1.24.4)
[2025-05-02T18:24:59.618+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvfc6akuie/requirements.txt (line 1)) (23.2)
[2025-05-02T18:24:59.619+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvfc6akuie/requirements.txt (line 1)) (2.0.3)
[2025-05-02T18:24:59.620+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvfc6akuie/requirements.txt (line 1)) (14.0.2)
[2025-05-02T18:24:59.620+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvfc6akuie/requirements.txt (line 1)) (4.9.0)
[2025-05-02T18:24:59.624+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venvfc6akuie/requirements.txt (line 2)) (0.10.0)
[2025-05-02T18:24:59.625+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venvfc6akuie/requirements.txt (line 2)) (0.11.5)
[2025-05-02T18:24:59.662+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (2.17.2)
[2025-05-02T18:24:59.662+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (2.2.5)
[2025-05-02T18:24:59.663+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (1.13.1)
[2025-05-02T18:24:59.663+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (7.0.0)
[2025-05-02T18:24:59.664+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (3.4.3)
[2025-05-02T18:24:59.664+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (3.5.2)
[2025-05-02T18:24:59.665+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (3.7.5)
[2025-05-02T18:24:59.666+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (1.10.1)
[2025-05-02T18:24:59.666+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (1.4.51)
[2025-05-02T18:24:59.667+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (3.1.3)
[2025-05-02T18:24:59.668+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (21.2.0)
[2025-05-02T18:24:59.703+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (5.3.2)
[2025-05-02T18:24:59.704+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (8.1.7)
[2025-05-02T18:24:59.704+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (3.1.1)
[2025-05-02T18:24:59.705+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (0.51.0)
[2025-05-02T18:24:59.705+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (3.1.44)
[2025-05-02T18:24:59.706+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (6.11.0)
[2025-05-02T18:24:59.706+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (1.22.0)
[2025-05-02T18:24:59.707+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (1.22.0)
[2025-05-02T18:24:59.707+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (4.25.2)
[2025-05-02T18:24:59.708+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (6.0.1)
[2025-05-02T18:24:59.708+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (2.31.0)
[2025-05-02T18:24:59.709+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (0.4.4)
[2025-05-02T18:24:59.734+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn->-r /tmp/venvfc6akuie/requirements.txt (line 4)) (1.4.2)
[2025-05-02T18:24:59.735+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn->-r /tmp/venvfc6akuie/requirements.txt (line 4)) (3.5.0)
[2025-05-02T18:24:59.741+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (1.3.0)
[2025-05-02T18:24:59.741+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (5.13.0)
[2025-05-02T18:24:59.748+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvfc6akuie/requirements.txt (line 1)) (2.8.2)
[2025-05-02T18:24:59.750+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvfc6akuie/requirements.txt (line 1)) (1.26.18)
[2025-05-02T18:24:59.760+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (2.2.3)
[2025-05-02T18:24:59.761+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (2.1.2)
[2025-05-02T18:24:59.789+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (3.2.6)
[2025-05-02T18:24:59.790+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (3.2.0)
[2025-05-02T18:24:59.798+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (2.1.3)
[2025-05-02T18:24:59.817+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (1.1.1)
[2025-05-02T18:24:59.818+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (0.12.1)
[2025-05-02T18:24:59.818+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (4.57.0)
[2025-05-02T18:24:59.819+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (1.4.7)
[2025-05-02T18:24:59.819+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (10.4.0)
[2025-05-02T18:24:59.820+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (3.1.1)
[2025-05-02T18:24:59.887+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvfc6akuie/requirements.txt (line 1)) (2023.3.post1)
[2025-05-02T18:24:59.889+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvfc6akuie/requirements.txt (line 1)) (2023.4)
[2025-05-02T18:24:59.963+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (3.0.3)
[2025-05-02T18:25:00.020+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (2.26.2)
[2025-05-02T18:25:00.070+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (4.0.12)
[2025-05-02T18:25:00.104+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (3.17.0)
[2025-05-02T18:25:00.135+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (1.2.14)
[2025-05-02T18:25:00.141+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (0.43b0)
[2025-05-02T18:25:00.175+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvfc6akuie/requirements.txt (line 1)) (1.16.0)
[2025-05-02T18:25:00.193+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (3.3.2)
[2025-05-02T18:25:00.194+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (3.6)
[2025-05-02T18:25:00.194+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (2023.11.17)
[2025-05-02T18:25:00.256+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (1.16.0)
[2025-05-02T18:25:00.262+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (5.0.2)
[2025-05-02T18:25:00.276+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (0.3.0)
[2025-05-02T18:25:00.277+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (4.9)
[2025-05-02T18:25:00.313+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvfc6akuie/requirements.txt (line 3)) (0.5.1)
[2025-05-02T18:25:00.365+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-02T18:25:00.386+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 20.0 MB/s eta 0:00:00
[2025-05-02T18:25:02.269+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-02T18:25:02.473+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-02T18:25:02.557+0000] {process_utils.py:190} INFO - 
[2025-05-02T18:25:02.558+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-02T18:25:02.559+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-02T18:25:02.699+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvfc6akuie/bin/python /tmp/venv-call8mixb44j/script.py /tmp/venv-call8mixb44j/script.in /tmp/venv-call8mixb44j/script.out /tmp/venv-call8mixb44j/string_args.txt /tmp/venv-call8mixb44j/termination.log
[2025-05-02T18:25:02.705+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T18:25:03.334+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-02T18:25:04.906+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:04.905+0000[0m] {[34mscript.py:[0m52} INFO[0m - Starting to read training and testing datasets from S3/Minio[0m
[2025-05-02T18:25:04.918+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:04.918+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T18:25:04.988+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:04.987+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T18:25:05.040+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.040+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T18:25:05.200+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.200+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T18:25:05.232+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.232+0000[0m] {[34mscript.py:[0m58} INFO[0m - Training and testing datasets loaded successfully from S3/Minio[0m
[2025-05-02T18:25:05.234+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.232+0000[0m] {[34mscript.py:[0m59} INFO[0m - Training set shape: (3577, 16), Testing set shape: (1533, 16)[0m
[2025-05-02T18:25:05.234+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.233+0000[0m] {[34mscript.py:[0m64} INFO[0m - Initializing the StandardScaler[0m
[2025-05-02T18:25:05.240+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.239+0000[0m] {[34mscript.py:[0m81} INFO[0m - Data normalization completed successfully using StandardScaler[0m
[2025-05-02T18:25:05.240+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.240+0000[0m] {[34mscript.py:[0m85} INFO[0m - Scaler mean: [4.32504333e+01 9.61699748e-02 5.39558289e-02 1.05845801e+02
[2025-05-02T18:25:05.241+0000] {process_utils.py:190} INFO -  3.04166620e+01]... (showing first 5 elements)[0m
[2025-05-02T18:25:05.241+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.240+0000[0m] {[34mscript.py:[0m86} INFO[0m - Scaler scale: [22.48993273  0.2948242   0.22593051 44.5820797  10.73996514]... (showing first 5 elements)[0m
[2025-05-02T18:25:05.244+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.244+0000[0m] {[34mscript.py:[0m105} INFO[0m - Scaled data successfully converted to DataFrame[0m
[2025-05-02T18:25:05.244+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.244+0000[0m] {[34mscript.py:[0m110} INFO[0m - Starting to save scaled training and testing datasets to S3/Minio[0m
[2025-05-02T18:25:05.252+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.252+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T18:25:05.303+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.303+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T18:25:05.376+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.375+0000[0m] {[34mscript.py:[0m115} INFO[0m - Scaled training data saved successfully to s3://data/train/stroke_data_X_train_scaled.csv[0m
[2025-05-02T18:25:05.383+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.383+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T18:25:05.433+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.433+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T18:25:05.467+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.466+0000[0m] {[34mscript.py:[0m118} INFO[0m - Scaled testing data saved successfully to s3://data/test/stroke_data_X_test_scaled.csv[0m
[2025-05-02T18:25:05.467+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.467+0000[0m] {[34mscript.py:[0m123} INFO[0m - Updating dataset information with scaler details[0m
[2025-05-02T18:25:05.474+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.474+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T18:25:05.644+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.644+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T18:25:05.656+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.656+0000[0m] {[34mscript.py:[0m134} INFO[0m - Existing dataset information loaded from S3/Minio[0m
[2025-05-02T18:25:05.663+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.663+0000[0m] {[34mscript.py:[0m153} INFO[0m - Dataset information updated successfully in S3/Minio with scaler details[0m
[2025-05-02T18:25:05.663+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.663+0000[0m] {[34mscript.py:[0m159} INFO[0m - Logging scaler details and dataset info to MLflow[0m
[2025-05-02T18:25:05.942+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.942+0000[0m] {[34mscript.py:[0m201} INFO[0m - Scaler details and dataset info logged to MLflow successfully in run: normalize_data_20250502_182505[0m
[2025-05-02T18:25:05.963+0000] {process_utils.py:190} INFO - 2025/05/02 18:25:05 INFO mlflow.tracking._tracking_service.client: 🏃 View run normalize_data_20250502_182505 at: http://mlflow:5000/#/experiments/1/runs/88b30e4a7ede492ba49dff6393cd6a0f.
[2025-05-02T18:25:05.964+0000] {process_utils.py:190} INFO - 2025/05/02 18:25:05 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-02T18:25:05.979+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:25:05.978+0000[0m] {[34mscript.py:[0m203} INFO[0m - Data normalization process completed successfully[0m
[2025-05-02T18:25:06.367+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-02T18:25:06.375+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=normalize_data, execution_date=20250501T000000, start_date=20250502T182457, end_date=20250502T182506
[2025-05-02T18:25:06.419+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-02T18:25:06.440+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-02T22:43:30.704+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T22:43:30.716+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T22:43:30.717+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-02T22:43:30.730+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): normalize_data> on 2025-05-01 00:00:00+00:00
[2025-05-02T22:43:30.736+0000] {standard_task_runner.py:60} INFO - Started process 677 to run task
[2025-05-02T22:43:30.738+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'normalize_data', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmppk4wzt44']
[2025-05-02T22:43:30.741+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask normalize_data
[2025-05-02T22:43:30.793+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-01T00:00:00+00:00 [running]> on host 06c6f1d995e0
[2025-05-02T22:43:30.862+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='normalize_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-02T22:43:30.865+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvf2_ljckf --system-site-packages --python=python
[2025-05-02T22:43:30.873+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T22:43:31.682+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 434ms
[2025-05-02T22:43:31.684+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvf2_ljckf, clear=False, no_vcs_ignore=False, global=True)
[2025-05-02T22:43:31.684+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmpv2g7j4yf)
[2025-05-02T22:43:31.685+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-02T22:43:31.686+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-02T22:43:31.728+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvf2_ljckf/bin/pip install -r /tmp/venvf2_ljckf/requirements.txt
[2025-05-02T22:43:31.740+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T22:43:32.705+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-02T22:43:33.059+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venvf2_ljckf/requirements.txt (line 1))
[2025-05-02T22:43:33.108+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-02T22:43:33.110+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvf2_ljckf/requirements.txt (line 2)) (1.37.38)
[2025-05-02T22:43:33.111+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvf2_ljckf/requirements.txt (line 3)) (2.17.2)
[2025-05-02T22:43:33.113+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvf2_ljckf/requirements.txt (line 4)) (1.3.2)
[2025-05-02T22:43:33.163+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvf2_ljckf/requirements.txt (line 1)) (1.37.38)
[2025-05-02T22:43:33.165+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvf2_ljckf/requirements.txt (line 1)) (1.24.4)
[2025-05-02T22:43:33.166+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvf2_ljckf/requirements.txt (line 1)) (23.2)
[2025-05-02T22:43:33.168+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvf2_ljckf/requirements.txt (line 1)) (2.0.3)
[2025-05-02T22:43:33.169+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvf2_ljckf/requirements.txt (line 1)) (14.0.2)
[2025-05-02T22:43:33.170+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvf2_ljckf/requirements.txt (line 1)) (4.9.0)
[2025-05-02T22:43:33.179+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venvf2_ljckf/requirements.txt (line 2)) (0.10.0)
[2025-05-02T22:43:33.180+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venvf2_ljckf/requirements.txt (line 2)) (0.11.5)
[2025-05-02T22:43:33.233+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (2.17.2)
[2025-05-02T22:43:33.234+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (2.2.5)
[2025-05-02T22:43:33.236+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (1.13.1)
[2025-05-02T22:43:33.236+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (7.0.0)
[2025-05-02T22:43:33.237+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (3.4.3)
[2025-05-02T22:43:33.238+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (3.5.2)
[2025-05-02T22:43:33.239+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (3.7.5)
[2025-05-02T22:43:33.240+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (1.10.1)
[2025-05-02T22:43:33.241+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (1.4.51)
[2025-05-02T22:43:33.242+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (3.1.3)
[2025-05-02T22:43:33.243+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (21.2.0)
[2025-05-02T22:43:33.296+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (5.3.2)
[2025-05-02T22:43:33.297+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (8.1.7)
[2025-05-02T22:43:33.297+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (3.1.1)
[2025-05-02T22:43:33.298+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (0.51.0)
[2025-05-02T22:43:33.298+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (3.1.44)
[2025-05-02T22:43:33.299+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (6.11.0)
[2025-05-02T22:43:33.300+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (1.22.0)
[2025-05-02T22:43:33.300+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (1.22.0)
[2025-05-02T22:43:33.301+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (4.25.2)
[2025-05-02T22:43:33.302+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (6.0.1)
[2025-05-02T22:43:33.302+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (2.31.0)
[2025-05-02T22:43:33.303+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (0.4.4)
[2025-05-02T22:43:33.346+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn->-r /tmp/venvf2_ljckf/requirements.txt (line 4)) (1.4.2)
[2025-05-02T22:43:33.348+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn->-r /tmp/venvf2_ljckf/requirements.txt (line 4)) (3.5.0)
[2025-05-02T22:43:33.356+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (1.3.0)
[2025-05-02T22:43:33.357+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (5.13.0)
[2025-05-02T22:43:33.365+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvf2_ljckf/requirements.txt (line 1)) (2.8.2)
[2025-05-02T22:43:33.368+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvf2_ljckf/requirements.txt (line 1)) (1.26.18)
[2025-05-02T22:43:33.384+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (2.2.3)
[2025-05-02T22:43:33.387+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (2.1.2)
[2025-05-02T22:43:33.436+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (3.2.6)
[2025-05-02T22:43:33.437+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (3.2.0)
[2025-05-02T22:43:33.452+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (2.1.3)
[2025-05-02T22:43:33.481+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (1.1.1)
[2025-05-02T22:43:33.482+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (0.12.1)
[2025-05-02T22:43:33.483+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (4.57.0)
[2025-05-02T22:43:33.484+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (1.4.7)
[2025-05-02T22:43:33.485+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (10.4.0)
[2025-05-02T22:43:33.486+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (3.1.1)
[2025-05-02T22:43:33.595+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvf2_ljckf/requirements.txt (line 1)) (2023.3.post1)
[2025-05-02T22:43:33.596+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvf2_ljckf/requirements.txt (line 1)) (2023.4)
[2025-05-02T22:43:33.728+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (3.0.3)
[2025-05-02T22:43:33.819+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (2.26.2)
[2025-05-02T22:43:33.916+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (4.0.12)
[2025-05-02T22:43:33.981+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (3.17.0)
[2025-05-02T22:43:34.042+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (1.2.14)
[2025-05-02T22:43:34.057+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (0.43b0)
[2025-05-02T22:43:34.121+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvf2_ljckf/requirements.txt (line 1)) (1.16.0)
[2025-05-02T22:43:34.160+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (3.3.2)
[2025-05-02T22:43:34.169+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (3.6)
[2025-05-02T22:43:34.170+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (2023.11.17)
[2025-05-02T22:43:34.266+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (1.16.0)
[2025-05-02T22:43:34.277+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (5.0.2)
[2025-05-02T22:43:34.295+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (0.3.0)
[2025-05-02T22:43:34.296+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (4.9)
[2025-05-02T22:43:34.348+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvf2_ljckf/requirements.txt (line 3)) (0.5.1)
[2025-05-02T22:43:34.398+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-02T22:43:34.431+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 13.0 MB/s eta 0:00:00
[2025-05-02T22:43:36.938+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-02T22:43:37.253+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-02T22:43:37.364+0000] {process_utils.py:190} INFO - 
[2025-05-02T22:43:37.365+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-02T22:43:37.366+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-02T22:43:37.625+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvf2_ljckf/bin/python /tmp/venv-callga6bgdyj/script.py /tmp/venv-callga6bgdyj/script.in /tmp/venv-callga6bgdyj/script.out /tmp/venv-callga6bgdyj/string_args.txt /tmp/venv-callga6bgdyj/termination.log
[2025-05-02T22:43:37.635+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T22:43:38.446+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-02T22:43:40.499+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:40.498+0000[0m] {[34mscript.py:[0m52} INFO[0m - Starting to read training and testing datasets from S3/Minio[0m
[2025-05-02T22:43:40.516+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:40.515+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T22:43:40.587+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:40.587+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T22:43:40.657+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:40.657+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T22:43:40.839+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:40.838+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T22:43:40.886+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:40.885+0000[0m] {[34mscript.py:[0m58} INFO[0m - Training and testing datasets loaded successfully from S3/Minio[0m
[2025-05-02T22:43:40.887+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:40.886+0000[0m] {[34mscript.py:[0m59} INFO[0m - Training set shape: (3577, 16), Testing set shape: (1533, 16)[0m
[2025-05-02T22:43:40.888+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:40.886+0000[0m] {[34mscript.py:[0m64} INFO[0m - Initializing the StandardScaler[0m
[2025-05-02T22:43:40.895+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:40.895+0000[0m] {[34mscript.py:[0m81} INFO[0m - Data normalization completed successfully using StandardScaler[0m
[2025-05-02T22:43:40.896+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:40.895+0000[0m] {[34mscript.py:[0m85} INFO[0m - Scaler mean: [4.32504333e+01 9.61699748e-02 5.39558289e-02 1.05845801e+02
[2025-05-02T22:43:40.897+0000] {process_utils.py:190} INFO -  3.04166620e+01]... (showing first 5 elements)[0m
[2025-05-02T22:43:40.898+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:40.896+0000[0m] {[34mscript.py:[0m86} INFO[0m - Scaler scale: [22.48993273  0.2948242   0.22593051 44.5820797  10.73996514]... (showing first 5 elements)[0m
[2025-05-02T22:43:40.901+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:40.900+0000[0m] {[34mscript.py:[0m105} INFO[0m - Scaled data successfully converted to DataFrame[0m
[2025-05-02T22:43:40.901+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:40.901+0000[0m] {[34mscript.py:[0m110} INFO[0m - Starting to save scaled training and testing datasets to S3/Minio[0m
[2025-05-02T22:43:40.912+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:40.912+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T22:43:40.967+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:40.967+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T22:43:41.060+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:41.060+0000[0m] {[34mscript.py:[0m115} INFO[0m - Scaled training data saved successfully to s3://data/train/stroke_data_X_train_scaled.csv[0m
[2025-05-02T22:43:41.070+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:41.069+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T22:43:41.134+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:41.134+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T22:43:41.221+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:41.220+0000[0m] {[34mscript.py:[0m118} INFO[0m - Scaled testing data saved successfully to s3://data/test/stroke_data_X_test_scaled.csv[0m
[2025-05-02T22:43:41.222+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:41.221+0000[0m] {[34mscript.py:[0m123} INFO[0m - Updating dataset information with scaler details[0m
[2025-05-02T22:43:41.231+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:41.231+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T22:43:41.453+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:41.453+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T22:43:41.473+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:41.473+0000[0m] {[34mscript.py:[0m134} INFO[0m - Existing dataset information loaded from S3/Minio[0m
[2025-05-02T22:43:41.486+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:41.485+0000[0m] {[34mscript.py:[0m153} INFO[0m - Dataset information updated successfully in S3/Minio with scaler details[0m
[2025-05-02T22:43:41.486+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:41.485+0000[0m] {[34mscript.py:[0m159} INFO[0m - Logging scaler details and dataset info to MLflow[0m
[2025-05-02T22:43:42.363+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:42.363+0000[0m] {[34mscript.py:[0m201} INFO[0m - Scaler details and dataset info logged to MLflow successfully in run: normalize_data_20250502_224341[0m
[2025-05-02T22:43:42.400+0000] {process_utils.py:190} INFO - 2025/05/02 22:43:42 INFO mlflow.tracking._tracking_service.client: 🏃 View run normalize_data_20250502_224341 at: http://mlflow:5000/#/experiments/1/runs/759a8cc5155b470faa80d9a1be5b784f.
[2025-05-02T22:43:42.401+0000] {process_utils.py:190} INFO - 2025/05/02 22:43:42 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-02T22:43:42.436+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:42.436+0000[0m] {[34mscript.py:[0m203} INFO[0m - Data normalization process completed successfully[0m
[2025-05-02T22:43:42.954+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-02T22:43:42.966+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=normalize_data, execution_date=20250501T000000, start_date=20250502T224330, end_date=20250502T224342
[2025-05-02T22:43:43.053+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-02T22:43:43.072+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
