[2025-05-02T18:24:24.968+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T18:24:24.979+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T18:24:25.005+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-02T18:24:25.017+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): get_original_data> on 2025-05-01 00:00:00+00:00
[2025-05-02T18:24:25.026+0000] {standard_task_runner.py:60} INFO - Started process 1721 to run task
[2025-05-02T18:24:25.029+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'get_original_data', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmp3bz9g7a0']
[2025-05-02T18:24:25.031+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask get_original_data
[2025-05-02T18:24:25.075+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-01T00:00:00+00:00 [running]> on host 82b06739c44f
[2025-05-02T18:24:25.136+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='get_original_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-02T18:24:25.139+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv2dv2r0th --system-site-packages --python=python
[2025-05-02T18:24:25.146+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T18:24:25.942+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 418ms
[2025-05-02T18:24:25.943+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv2dv2r0th, clear=False, no_vcs_ignore=False, global=True)
[2025-05-02T18:24:25.944+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmprbyzf2yc)
[2025-05-02T18:24:25.944+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-02T18:24:25.944+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-02T18:24:25.967+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv2dv2r0th/bin/pip install -r /tmp/venv2dv2r0th/requirements.txt
[2025-05-02T18:24:25.978+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T18:24:26.635+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-02T18:24:26.912+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venv2dv2r0th/requirements.txt (line 1))
[2025-05-02T18:24:26.962+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-02T18:24:26.966+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv2dv2r0th/requirements.txt (line 2)) (2.17.2)
[2025-05-02T18:24:26.966+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv2dv2r0th/requirements.txt (line 3)) (2.0.3)
[2025-05-02T18:24:27.002+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv2dv2r0th/requirements.txt (line 1)) (1.37.38)
[2025-05-02T18:24:27.003+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv2dv2r0th/requirements.txt (line 1)) (1.37.38)
[2025-05-02T18:24:27.004+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv2dv2r0th/requirements.txt (line 1)) (1.24.4)
[2025-05-02T18:24:27.004+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv2dv2r0th/requirements.txt (line 1)) (23.2)
[2025-05-02T18:24:27.005+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv2dv2r0th/requirements.txt (line 1)) (14.0.2)
[2025-05-02T18:24:27.006+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv2dv2r0th/requirements.txt (line 1)) (4.9.0)
[2025-05-02T18:24:27.044+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (2.17.2)
[2025-05-02T18:24:27.053+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (2.2.5)
[2025-05-02T18:24:27.058+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (1.13.1)
[2025-05-02T18:24:27.063+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (7.0.0)
[2025-05-02T18:24:27.066+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (3.4.3)
[2025-05-02T18:24:27.067+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (3.5.2)
[2025-05-02T18:24:27.068+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (3.7.5)
[2025-05-02T18:24:27.069+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (1.3.2)
[2025-05-02T18:24:27.071+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (1.10.1)
[2025-05-02T18:24:27.072+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (1.4.51)
[2025-05-02T18:24:27.073+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (3.1.3)
[2025-05-02T18:24:27.073+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (21.2.0)
[2025-05-02T18:24:27.085+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (5.3.2)
[2025-05-02T18:24:27.086+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (8.1.7)
[2025-05-02T18:24:27.087+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (3.1.1)
[2025-05-02T18:24:27.087+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (0.51.0)
[2025-05-02T18:24:27.088+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (3.1.44)
[2025-05-02T18:24:27.088+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (6.11.0)
[2025-05-02T18:24:27.089+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (1.22.0)
[2025-05-02T18:24:27.090+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (1.22.0)
[2025-05-02T18:24:27.091+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (4.25.2)
[2025-05-02T18:24:27.091+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (6.0.1)
[2025-05-02T18:24:27.092+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (2.31.0)
[2025-05-02T18:24:27.092+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (0.4.4)
[2025-05-02T18:24:27.156+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venv2dv2r0th/requirements.txt (line 3)) (2.8.2)
[2025-05-02T18:24:27.157+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venv2dv2r0th/requirements.txt (line 3)) (2023.3.post1)
[2025-05-02T18:24:27.157+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venv2dv2r0th/requirements.txt (line 3)) (2023.4)
[2025-05-02T18:24:27.178+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (1.3.0)
[2025-05-02T18:24:27.179+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (5.13.0)
[2025-05-02T18:24:27.184+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venv2dv2r0th/requirements.txt (line 1)) (0.10.0)
[2025-05-02T18:24:27.184+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venv2dv2r0th/requirements.txt (line 1)) (0.11.5)
[2025-05-02T18:24:27.190+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venv2dv2r0th/requirements.txt (line 1)) (1.26.18)
[2025-05-02T18:24:27.201+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (2.2.3)
[2025-05-02T18:24:27.202+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (2.1.2)
[2025-05-02T18:24:27.217+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (3.2.6)
[2025-05-02T18:24:27.218+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (3.2.0)
[2025-05-02T18:24:27.226+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (2.1.3)
[2025-05-02T18:24:27.242+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (1.1.1)
[2025-05-02T18:24:27.243+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (0.12.1)
[2025-05-02T18:24:27.243+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (4.57.0)
[2025-05-02T18:24:27.244+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (1.4.7)
[2025-05-02T18:24:27.244+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (10.4.0)
[2025-05-02T18:24:27.245+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (3.1.1)
[2025-05-02T18:24:27.255+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas->-r /tmp/venv2dv2r0th/requirements.txt (line 3)) (1.16.0)
[2025-05-02T18:24:27.283+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (1.4.2)
[2025-05-02T18:24:27.284+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (3.5.0)
[2025-05-02T18:24:27.347+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (3.0.3)
[2025-05-02T18:24:27.404+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (2.26.2)
[2025-05-02T18:24:27.449+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (4.0.12)
[2025-05-02T18:24:27.482+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (3.17.0)
[2025-05-02T18:24:27.521+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (1.2.14)
[2025-05-02T18:24:27.528+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (0.43b0)
[2025-05-02T18:24:27.569+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (3.3.2)
[2025-05-02T18:24:27.570+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (3.6)
[2025-05-02T18:24:27.571+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (2023.11.17)
[2025-05-02T18:24:27.641+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (1.16.0)
[2025-05-02T18:24:27.650+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (5.0.2)
[2025-05-02T18:24:27.663+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (0.3.0)
[2025-05-02T18:24:27.664+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (4.9)
[2025-05-02T18:24:27.699+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv2dv2r0th/requirements.txt (line 2)) (0.5.1)
[2025-05-02T18:24:27.743+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-02T18:24:27.773+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 13.4 MB/s eta 0:00:00
[2025-05-02T18:24:29.808+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-02T18:24:30.120+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-02T18:24:30.217+0000] {process_utils.py:190} INFO - 
[2025-05-02T18:24:30.218+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-02T18:24:30.218+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-02T18:24:30.439+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv2dv2r0th/bin/python /tmp/venv-call9k5h4pry/script.py /tmp/venv-call9k5h4pry/script.in /tmp/venv-call9k5h4pry/script.out /tmp/venv-call9k5h4pry/string_args.txt /tmp/venv-call9k5h4pry/termination.log
[2025-05-02T18:24:30.448+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T18:24:31.183+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-02T18:24:35.389+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:35.385+0000[0m] {[34mscript.py:[0m49} INFO[0m - Starting to read the dataset from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-02T18:24:35.423+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:35.422+0000[0m] {[34mscript.py:[0m59} INFO[0m - Dataset read successfully from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-02T18:24:35.424+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:35.423+0000[0m] {[34mscript.py:[0m60} INFO[0m - Dataset shape: (5110, 12)[0m
[2025-05-02T18:24:35.426+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:35.426+0000[0m] {[34mscript.py:[0m76} INFO[0m - Dataset columns: ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke'][0m
[2025-05-02T18:24:35.471+0000] {process_utils.py:190} INFO - 2025/05/02 18:24:35 INFO mlflow.tracking.fluent: Experiment with name 'Stroke Prediction' does not exist. Creating a new experiment.
[2025-05-02T18:24:36.163+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:36.162+0000[0m] {[34mscript.py:[0m106} INFO[0m - Logged dataset information to MLflow in run: get_data_20250502_182435[0m
[2025-05-02T18:24:36.195+0000] {process_utils.py:190} INFO - 2025/05/02 18:24:36 INFO mlflow.tracking._tracking_service.client: 🏃 View run get_data_20250502_182435 at: http://mlflow:5000/#/experiments/1/runs/580910a3fdbc4c1195d6067f3436c1d1.
[2025-05-02T18:24:36.196+0000] {process_utils.py:190} INFO - 2025/05/02 18:24:36 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-02T18:24:36.213+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:36.213+0000[0m] {[34mscript.py:[0m112} INFO[0m - Starting to save the dataset to S3/Minio at s3://data/raw/stroke_data.csv[0m
[2025-05-02T18:24:36.223+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:36.223+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T18:24:36.390+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:36.390+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T18:24:36.445+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:36.444+0000[0m] {[34mscript.py:[0m117} INFO[0m - Dataset saved successfully to s3://data/raw/stroke_data.csv[0m
[2025-05-02T18:24:36.761+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-02T18:24:36.770+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=get_original_data, execution_date=20250501T000000, start_date=20250502T182424, end_date=20250502T182436
[2025-05-02T18:24:36.802+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-02T18:24:36.825+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-02T22:42:42.248+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T22:42:42.255+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T22:42:42.256+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-02T22:42:42.268+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): get_original_data> on 2025-05-01 00:00:00+00:00
[2025-05-02T22:42:42.273+0000] {standard_task_runner.py:60} INFO - Started process 416 to run task
[2025-05-02T22:42:42.276+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'get_original_data', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmp7kzebrcz']
[2025-05-02T22:42:42.278+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask get_original_data
[2025-05-02T22:42:42.331+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-01T00:00:00+00:00 [running]> on host 06c6f1d995e0
[2025-05-02T22:42:42.403+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='get_original_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-02T22:42:42.406+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvpvxmxtts --system-site-packages --python=python
[2025-05-02T22:42:42.414+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T22:42:43.495+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 628ms
[2025-05-02T22:42:43.496+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvpvxmxtts, clear=False, no_vcs_ignore=False, global=True)
[2025-05-02T22:42:43.496+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmps2_onh4n)
[2025-05-02T22:42:43.497+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-02T22:42:43.497+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-02T22:42:43.528+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvpvxmxtts/bin/pip install -r /tmp/venvpvxmxtts/requirements.txt
[2025-05-02T22:42:43.535+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T22:42:44.331+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-02T22:42:44.828+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venvpvxmxtts/requirements.txt (line 1))
[2025-05-02T22:42:44.919+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-02T22:42:44.921+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvpvxmxtts/requirements.txt (line 2)) (2.17.2)
[2025-05-02T22:42:44.922+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvpvxmxtts/requirements.txt (line 3)) (2.0.3)
[2025-05-02T22:42:44.958+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvpvxmxtts/requirements.txt (line 1)) (1.37.38)
[2025-05-02T22:42:44.959+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvpvxmxtts/requirements.txt (line 1)) (1.37.38)
[2025-05-02T22:42:44.960+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvpvxmxtts/requirements.txt (line 1)) (1.24.4)
[2025-05-02T22:42:44.961+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvpvxmxtts/requirements.txt (line 1)) (23.2)
[2025-05-02T22:42:44.962+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvpvxmxtts/requirements.txt (line 1)) (14.0.2)
[2025-05-02T22:42:44.962+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvpvxmxtts/requirements.txt (line 1)) (4.9.0)
[2025-05-02T22:42:45.002+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (2.17.2)
[2025-05-02T22:42:45.003+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (2.2.5)
[2025-05-02T22:42:45.004+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (1.13.1)
[2025-05-02T22:42:45.004+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (7.0.0)
[2025-05-02T22:42:45.005+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (3.4.3)
[2025-05-02T22:42:45.006+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (3.5.2)
[2025-05-02T22:42:45.006+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (3.7.5)
[2025-05-02T22:42:45.007+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (1.3.2)
[2025-05-02T22:42:45.008+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (1.10.1)
[2025-05-02T22:42:45.010+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (1.4.51)
[2025-05-02T22:42:45.011+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (3.1.3)
[2025-05-02T22:42:45.012+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (21.2.0)
[2025-05-02T22:42:45.051+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (5.3.2)
[2025-05-02T22:42:45.052+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (8.1.7)
[2025-05-02T22:42:45.053+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (3.1.1)
[2025-05-02T22:42:45.054+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (0.51.0)
[2025-05-02T22:42:45.055+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (3.1.44)
[2025-05-02T22:42:45.056+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (6.11.0)
[2025-05-02T22:42:45.056+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (1.22.0)
[2025-05-02T22:42:45.057+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (1.22.0)
[2025-05-02T22:42:45.058+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (4.25.2)
[2025-05-02T22:42:45.058+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (6.0.1)
[2025-05-02T22:42:45.059+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (2.31.0)
[2025-05-02T22:42:45.059+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (0.4.4)
[2025-05-02T22:42:45.130+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvpvxmxtts/requirements.txt (line 3)) (2.8.2)
[2025-05-02T22:42:45.131+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvpvxmxtts/requirements.txt (line 3)) (2023.3.post1)
[2025-05-02T22:42:45.131+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvpvxmxtts/requirements.txt (line 3)) (2023.4)
[2025-05-02T22:42:45.157+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (1.3.0)
[2025-05-02T22:42:45.158+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (5.13.0)
[2025-05-02T22:42:45.162+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvpvxmxtts/requirements.txt (line 1)) (0.10.0)
[2025-05-02T22:42:45.163+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvpvxmxtts/requirements.txt (line 1)) (0.11.5)
[2025-05-02T22:42:45.169+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvpvxmxtts/requirements.txt (line 1)) (1.26.18)
[2025-05-02T22:42:45.181+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (2.2.3)
[2025-05-02T22:42:45.182+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (2.1.2)
[2025-05-02T22:42:45.197+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (3.2.6)
[2025-05-02T22:42:45.198+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (3.2.0)
[2025-05-02T22:42:45.207+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (2.1.3)
[2025-05-02T22:42:45.226+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (1.1.1)
[2025-05-02T22:42:45.227+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (0.12.1)
[2025-05-02T22:42:45.228+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (4.57.0)
[2025-05-02T22:42:45.229+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (1.4.7)
[2025-05-02T22:42:45.230+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (10.4.0)
[2025-05-02T22:42:45.231+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (3.1.1)
[2025-05-02T22:42:45.241+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas->-r /tmp/venvpvxmxtts/requirements.txt (line 3)) (1.16.0)
[2025-05-02T22:42:45.283+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (1.4.2)
[2025-05-02T22:42:45.285+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (3.5.0)
[2025-05-02T22:42:45.392+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (3.0.3)
[2025-05-02T22:42:45.467+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (2.26.2)
[2025-05-02T22:42:45.530+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (4.0.12)
[2025-05-02T22:42:45.647+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (3.17.0)
[2025-05-02T22:42:45.825+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (1.2.14)
[2025-05-02T22:42:45.849+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (0.43b0)
[2025-05-02T22:42:45.941+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (3.3.2)
[2025-05-02T22:42:45.944+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (3.6)
[2025-05-02T22:42:45.946+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (2023.11.17)
[2025-05-02T22:42:46.060+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (1.16.0)
[2025-05-02T22:42:46.068+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (5.0.2)
[2025-05-02T22:42:46.086+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (0.3.0)
[2025-05-02T22:42:46.087+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (4.9)
[2025-05-02T22:42:46.127+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvpvxmxtts/requirements.txt (line 2)) (0.5.1)
[2025-05-02T22:42:46.176+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-02T22:42:46.209+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 14.3 MB/s eta 0:00:00
[2025-05-02T22:42:48.892+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-02T22:42:49.242+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-02T22:42:49.351+0000] {process_utils.py:190} INFO - 
[2025-05-02T22:42:49.352+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-02T22:42:49.353+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-02T22:42:49.546+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvpvxmxtts/bin/python /tmp/venv-calld81tispo/script.py /tmp/venv-calld81tispo/script.in /tmp/venv-calld81tispo/script.out /tmp/venv-calld81tispo/string_args.txt /tmp/venv-calld81tispo/termination.log
[2025-05-02T22:42:49.553+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T22:42:50.251+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-02T22:42:54.297+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:42:54.296+0000[0m] {[34mscript.py:[0m49} INFO[0m - Starting to read the dataset from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-02T22:42:54.332+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:42:54.331+0000[0m] {[34mscript.py:[0m59} INFO[0m - Dataset read successfully from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-02T22:42:54.332+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:42:54.332+0000[0m] {[34mscript.py:[0m60} INFO[0m - Dataset shape: (5110, 12)[0m
[2025-05-02T22:42:54.335+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:42:54.335+0000[0m] {[34mscript.py:[0m76} INFO[0m - Dataset columns: ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke'][0m
[2025-05-02T22:42:57.125+0000] {process_utils.py:190} INFO - 2025/05/02 22:42:57 INFO mlflow.tracking.fluent: Experiment with name 'Stroke Prediction' does not exist. Creating a new experiment.
[2025-05-02T22:42:58.483+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:42:58.483+0000[0m] {[34mscript.py:[0m106} INFO[0m - Logged dataset information to MLflow in run: get_data_20250502_224257[0m
[2025-05-02T22:42:58.527+0000] {process_utils.py:190} INFO - 2025/05/02 22:42:58 INFO mlflow.tracking._tracking_service.client: 🏃 View run get_data_20250502_224257 at: http://mlflow:5000/#/experiments/1/runs/ae78e57668e2419c816aa0f62deb10a1.
[2025-05-02T22:42:58.528+0000] {process_utils.py:190} INFO - 2025/05/02 22:42:58 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-02T22:42:58.553+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:42:58.552+0000[0m] {[34mscript.py:[0m112} INFO[0m - Starting to save the dataset to S3/Minio at s3://data/raw/stroke_data.csv[0m
[2025-05-02T22:42:58.563+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:42:58.563+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T22:42:58.781+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:42:58.780+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T22:42:58.840+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:42:58.840+0000[0m] {[34mscript.py:[0m117} INFO[0m - Dataset saved successfully to s3://data/raw/stroke_data.csv[0m
[2025-05-02T22:42:59.264+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-02T22:42:59.278+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=get_original_data, execution_date=20250501T000000, start_date=20250502T224242, end_date=20250502T224259
[2025-05-02T22:42:59.326+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-02T22:42:59.370+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
