[2025-05-03T00:53:42.991+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T00:53:43.000+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T00:53:43.001+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-03T00:53:43.021+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): normalize_data> on 2025-05-02 00:00:00+00:00
[2025-05-03T00:53:43.027+0000] {standard_task_runner.py:60} INFO - Started process 551 to run task
[2025-05-03T00:53:43.029+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'normalize_data', 'scheduled__2025-05-02T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmpdo0hy4kh']
[2025-05-03T00:53:43.031+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask normalize_data
[2025-05-03T00:53:43.079+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-02T00:00:00+00:00 [running]> on host c624b4368fe1
[2025-05-03T00:53:43.147+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='normalize_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-02T00:00:00+00:00'
[2025-05-03T00:53:43.149+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvy62p72l9 --system-site-packages --python=python
[2025-05-03T00:53:43.156+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T00:53:44.018+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 435ms
[2025-05-03T00:53:44.019+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvy62p72l9, clear=False, no_vcs_ignore=False, global=True)
[2025-05-03T00:53:44.020+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmpsncxxj14)
[2025-05-03T00:53:44.021+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-03T00:53:44.022+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-03T00:53:44.049+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvy62p72l9/bin/pip install -r /tmp/venvy62p72l9/requirements.txt
[2025-05-03T00:53:44.056+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T00:53:44.758+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-03T00:53:44.997+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venvy62p72l9/requirements.txt (line 1))
[2025-05-03T00:53:45.049+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-03T00:53:45.051+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvy62p72l9/requirements.txt (line 2)) (1.37.38)
[2025-05-03T00:53:45.052+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvy62p72l9/requirements.txt (line 3)) (2.17.2)
[2025-05-03T00:53:45.052+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvy62p72l9/requirements.txt (line 4)) (1.3.2)
[2025-05-03T00:53:45.088+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvy62p72l9/requirements.txt (line 1)) (1.37.38)
[2025-05-03T00:53:45.090+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvy62p72l9/requirements.txt (line 1)) (1.24.4)
[2025-05-03T00:53:45.090+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvy62p72l9/requirements.txt (line 1)) (23.2)
[2025-05-03T00:53:45.091+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvy62p72l9/requirements.txt (line 1)) (2.0.3)
[2025-05-03T00:53:45.092+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvy62p72l9/requirements.txt (line 1)) (14.0.2)
[2025-05-03T00:53:45.092+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvy62p72l9/requirements.txt (line 1)) (4.9.0)
[2025-05-03T00:53:45.096+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venvy62p72l9/requirements.txt (line 2)) (0.10.0)
[2025-05-03T00:53:45.097+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venvy62p72l9/requirements.txt (line 2)) (0.11.5)
[2025-05-03T00:53:45.135+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (2.17.2)
[2025-05-03T00:53:45.135+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (2.2.5)
[2025-05-03T00:53:45.136+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (1.13.1)
[2025-05-03T00:53:45.136+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (7.0.0)
[2025-05-03T00:53:45.137+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (3.4.3)
[2025-05-03T00:53:45.137+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (3.5.2)
[2025-05-03T00:53:45.138+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (3.7.5)
[2025-05-03T00:53:45.139+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (1.10.1)
[2025-05-03T00:53:45.139+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (1.4.51)
[2025-05-03T00:53:45.140+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (3.1.3)
[2025-05-03T00:53:45.141+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (21.2.0)
[2025-05-03T00:53:45.179+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (5.3.2)
[2025-05-03T00:53:45.180+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (8.1.7)
[2025-05-03T00:53:45.180+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (3.1.1)
[2025-05-03T00:53:45.181+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (0.51.0)
[2025-05-03T00:53:45.182+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (3.1.44)
[2025-05-03T00:53:45.182+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (6.11.0)
[2025-05-03T00:53:45.183+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (1.22.0)
[2025-05-03T00:53:45.184+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (1.22.0)
[2025-05-03T00:53:45.185+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (4.25.2)
[2025-05-03T00:53:45.185+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (6.0.1)
[2025-05-03T00:53:45.185+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (2.31.0)
[2025-05-03T00:53:45.186+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (0.4.4)
[2025-05-03T00:53:45.213+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn->-r /tmp/venvy62p72l9/requirements.txt (line 4)) (1.4.2)
[2025-05-03T00:53:45.214+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn->-r /tmp/venvy62p72l9/requirements.txt (line 4)) (3.5.0)
[2025-05-03T00:53:45.221+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (1.3.0)
[2025-05-03T00:53:45.222+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (5.13.0)
[2025-05-03T00:53:45.232+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvy62p72l9/requirements.txt (line 1)) (2.8.2)
[2025-05-03T00:53:45.233+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvy62p72l9/requirements.txt (line 1)) (1.26.18)
[2025-05-03T00:53:45.246+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (2.2.3)
[2025-05-03T00:53:45.247+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (2.1.2)
[2025-05-03T00:53:45.279+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (3.2.6)
[2025-05-03T00:53:45.280+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (3.2.0)
[2025-05-03T00:53:45.289+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (2.1.3)
[2025-05-03T00:53:45.310+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (1.1.1)
[2025-05-03T00:53:45.311+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (0.12.1)
[2025-05-03T00:53:45.311+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (4.57.0)
[2025-05-03T00:53:45.312+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (1.4.7)
[2025-05-03T00:53:45.312+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (10.4.0)
[2025-05-03T00:53:45.313+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (3.1.1)
[2025-05-03T00:53:45.389+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvy62p72l9/requirements.txt (line 1)) (2023.3.post1)
[2025-05-03T00:53:45.390+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvy62p72l9/requirements.txt (line 1)) (2023.4)
[2025-05-03T00:53:45.473+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (3.0.3)
[2025-05-03T00:53:45.530+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (2.26.2)
[2025-05-03T00:53:45.578+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (4.0.12)
[2025-05-03T00:53:45.615+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (3.17.0)
[2025-05-03T00:53:45.649+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (1.2.14)
[2025-05-03T00:53:45.656+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (0.43b0)
[2025-05-03T00:53:45.695+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvy62p72l9/requirements.txt (line 1)) (1.16.0)
[2025-05-03T00:53:45.713+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (3.3.2)
[2025-05-03T00:53:45.714+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (3.6)
[2025-05-03T00:53:45.714+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (2023.11.17)
[2025-05-03T00:53:45.778+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (1.16.0)
[2025-05-03T00:53:45.786+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (5.0.2)
[2025-05-03T00:53:45.800+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (0.3.0)
[2025-05-03T00:53:45.801+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (4.9)
[2025-05-03T00:53:45.838+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvy62p72l9/requirements.txt (line 3)) (0.5.1)
[2025-05-03T00:53:45.879+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-03T00:53:45.970+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 23.0 MB/s eta 0:00:00
[2025-05-03T00:53:47.908+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-03T00:53:48.090+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-03T00:53:48.195+0000] {process_utils.py:190} INFO - 
[2025-05-03T00:53:48.196+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-03T00:53:48.197+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-03T00:53:48.397+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvy62p72l9/bin/python /tmp/venv-cally7gmriuq/script.py /tmp/venv-cally7gmriuq/script.in /tmp/venv-cally7gmriuq/script.out /tmp/venv-cally7gmriuq/string_args.txt /tmp/venv-cally7gmriuq/termination.log
[2025-05-03T00:53:48.407+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T00:53:49.107+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-03T00:53:50.835+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:50.834+0000[0m] {[34mscript.py:[0m52} INFO[0m - Starting to read training and testing datasets from S3/Minio[0m
[2025-05-03T00:53:50.846+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:50.845+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T00:53:50.903+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:50.902+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T00:53:50.952+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:50.952+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T00:53:51.092+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.091+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T00:53:51.125+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.124+0000[0m] {[34mscript.py:[0m58} INFO[0m - Training and testing datasets loaded successfully from S3/Minio[0m
[2025-05-03T00:53:51.125+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.125+0000[0m] {[34mscript.py:[0m59} INFO[0m - Training set shape: (3577, 16), Testing set shape: (1533, 16)[0m
[2025-05-03T00:53:51.126+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.125+0000[0m] {[34mscript.py:[0m64} INFO[0m - Initializing the StandardScaler[0m
[2025-05-03T00:53:51.132+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.132+0000[0m] {[34mscript.py:[0m81} INFO[0m - Data normalization completed successfully using StandardScaler[0m
[2025-05-03T00:53:51.133+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.132+0000[0m] {[34mscript.py:[0m85} INFO[0m - Scaler mean: [4.32504333e+01 9.61699748e-02 5.39558289e-02 1.05845801e+02
[2025-05-03T00:53:51.133+0000] {process_utils.py:190} INFO -  3.04166620e+01]... (showing first 5 elements)[0m
[2025-05-03T00:53:51.133+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.132+0000[0m] {[34mscript.py:[0m86} INFO[0m - Scaler scale: [22.48993273  0.2948242   0.22593051 44.5820797  10.73996514]... (showing first 5 elements)[0m
[2025-05-03T00:53:51.136+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.136+0000[0m] {[34mscript.py:[0m105} INFO[0m - Scaled data successfully converted to DataFrame[0m
[2025-05-03T00:53:51.136+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.136+0000[0m] {[34mscript.py:[0m110} INFO[0m - Starting to save scaled training and testing datasets to S3/Minio[0m
[2025-05-03T00:53:51.143+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.143+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T00:53:51.189+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.189+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T00:53:51.343+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.342+0000[0m] {[34mscript.py:[0m115} INFO[0m - Scaled training data saved successfully to s3://data/train/stroke_data_X_train_scaled.csv[0m
[2025-05-03T00:53:51.357+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.356+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T00:53:51.408+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.408+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T00:53:51.445+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.444+0000[0m] {[34mscript.py:[0m118} INFO[0m - Scaled testing data saved successfully to s3://data/test/stroke_data_X_test_scaled.csv[0m
[2025-05-03T00:53:51.446+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.445+0000[0m] {[34mscript.py:[0m123} INFO[0m - Updating dataset information with scaler details[0m
[2025-05-03T00:53:51.458+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.458+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T00:53:51.633+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:51.632+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T00:53:52.507+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:52.506+0000[0m] {[34mscript.py:[0m134} INFO[0m - Existing dataset information loaded from S3/Minio[0m
[2025-05-03T00:53:52.596+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:52.595+0000[0m] {[34mscript.py:[0m153} INFO[0m - Dataset information updated successfully in S3/Minio with scaler details[0m
[2025-05-03T00:53:52.597+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:52.596+0000[0m] {[34mscript.py:[0m159} INFO[0m - Logging scaler details and dataset info to MLflow[0m
[2025-05-03T00:53:53.232+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:53.231+0000[0m] {[34mscript.py:[0m201} INFO[0m - Scaler details and dataset info logged to MLflow successfully in run: normalize_data_20250503_005352[0m
[2025-05-03T00:53:53.270+0000] {process_utils.py:190} INFO - 2025/05/03 00:53:53 INFO mlflow.tracking._tracking_service.client: 🏃 View run normalize_data_20250503_005352 at: http://mlflow:5000/#/experiments/1/runs/5026499ea2e247bdbf45902d09177048.
[2025-05-03T00:53:53.271+0000] {process_utils.py:190} INFO - 2025/05/03 00:53:53 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-03T00:53:53.343+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:53.342+0000[0m] {[34mscript.py:[0m203} INFO[0m - Data normalization process completed successfully[0m
[2025-05-03T00:53:53.861+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-03T00:53:53.878+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=normalize_data, execution_date=20250502T000000, start_date=20250503T005342, end_date=20250503T005353
[2025-05-03T00:53:53.907+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-03T00:53:53.923+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T04:58:38.918+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T04:58:38.931+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T04:58:38.932+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-03T04:58:38.951+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): normalize_data> on 2025-05-02 00:00:00+00:00
[2025-05-03T04:58:38.956+0000] {standard_task_runner.py:60} INFO - Started process 950 to run task
[2025-05-03T04:58:38.958+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'normalize_data', 'scheduled__2025-05-02T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmpcygqzecw']
[2025-05-03T04:58:38.960+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask normalize_data
[2025-05-03T04:58:39.002+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-02T00:00:00+00:00 [running]> on host 75c2609a33dd
[2025-05-03T04:58:39.055+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='normalize_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-02T00:00:00+00:00'
[2025-05-03T04:58:39.057+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvp5bou6i9 --system-site-packages --python=python
[2025-05-03T04:58:39.063+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T04:58:39.629+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 300ms
[2025-05-03T04:58:39.630+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvp5bou6i9, clear=False, no_vcs_ignore=False, global=True)
[2025-05-03T04:58:39.630+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmp22rh4lx7)
[2025-05-03T04:58:39.630+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-03T04:58:39.631+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-03T04:58:39.655+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvp5bou6i9/bin/pip install -r /tmp/venvp5bou6i9/requirements.txt
[2025-05-03T04:58:39.662+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T04:58:40.320+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-03T04:58:40.531+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venvp5bou6i9/requirements.txt (line 1))
[2025-05-03T04:58:40.720+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-03T04:58:40.723+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvp5bou6i9/requirements.txt (line 2)) (1.37.38)
[2025-05-03T04:58:40.724+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvp5bou6i9/requirements.txt (line 3)) (2.17.2)
[2025-05-03T04:58:40.724+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvp5bou6i9/requirements.txt (line 4)) (1.3.2)
[2025-05-03T04:58:40.756+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvp5bou6i9/requirements.txt (line 1)) (1.37.38)
[2025-05-03T04:58:40.757+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvp5bou6i9/requirements.txt (line 1)) (1.24.4)
[2025-05-03T04:58:40.758+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvp5bou6i9/requirements.txt (line 1)) (23.2)
[2025-05-03T04:58:40.759+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvp5bou6i9/requirements.txt (line 1)) (2.0.3)
[2025-05-03T04:58:40.759+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvp5bou6i9/requirements.txt (line 1)) (14.0.2)
[2025-05-03T04:58:40.760+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvp5bou6i9/requirements.txt (line 1)) (4.9.0)
[2025-05-03T04:58:40.764+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venvp5bou6i9/requirements.txt (line 2)) (0.10.0)
[2025-05-03T04:58:40.764+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venvp5bou6i9/requirements.txt (line 2)) (0.11.5)
[2025-05-03T04:58:40.801+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (2.17.2)
[2025-05-03T04:58:40.802+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (2.2.5)
[2025-05-03T04:58:40.803+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (1.13.1)
[2025-05-03T04:58:40.803+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (7.0.0)
[2025-05-03T04:58:40.804+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (3.4.3)
[2025-05-03T04:58:40.804+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (3.5.2)
[2025-05-03T04:58:40.805+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (3.7.5)
[2025-05-03T04:58:40.806+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (1.10.1)
[2025-05-03T04:58:40.806+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (1.4.51)
[2025-05-03T04:58:40.807+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (3.1.3)
[2025-05-03T04:58:40.808+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (21.2.0)
[2025-05-03T04:58:40.843+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (5.3.2)
[2025-05-03T04:58:40.844+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (8.1.7)
[2025-05-03T04:58:40.845+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (3.1.1)
[2025-05-03T04:58:40.845+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (0.51.0)
[2025-05-03T04:58:40.845+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (3.1.44)
[2025-05-03T04:58:40.846+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (6.11.0)
[2025-05-03T04:58:40.846+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (1.22.0)
[2025-05-03T04:58:40.847+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (1.22.0)
[2025-05-03T04:58:40.847+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (4.25.2)
[2025-05-03T04:58:40.848+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (6.0.1)
[2025-05-03T04:58:40.849+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (2.31.0)
[2025-05-03T04:58:40.849+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (0.4.4)
[2025-05-03T04:58:40.873+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn->-r /tmp/venvp5bou6i9/requirements.txt (line 4)) (1.4.2)
[2025-05-03T04:58:40.874+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn->-r /tmp/venvp5bou6i9/requirements.txt (line 4)) (3.5.0)
[2025-05-03T04:58:40.880+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (1.3.0)
[2025-05-03T04:58:40.881+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (5.13.0)
[2025-05-03T04:58:40.886+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvp5bou6i9/requirements.txt (line 1)) (2.8.2)
[2025-05-03T04:58:40.887+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvp5bou6i9/requirements.txt (line 1)) (1.26.18)
[2025-05-03T04:58:40.898+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (2.2.3)
[2025-05-03T04:58:40.899+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (2.1.2)
[2025-05-03T04:58:40.930+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (3.2.6)
[2025-05-03T04:58:40.931+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (3.2.0)
[2025-05-03T04:58:40.941+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (2.1.3)
[2025-05-03T04:58:40.960+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (1.1.1)
[2025-05-03T04:58:40.961+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (0.12.1)
[2025-05-03T04:58:40.961+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (4.57.0)
[2025-05-03T04:58:40.962+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (1.4.7)
[2025-05-03T04:58:40.962+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (10.4.0)
[2025-05-03T04:58:40.963+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (3.1.1)
[2025-05-03T04:58:41.028+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvp5bou6i9/requirements.txt (line 1)) (2023.3.post1)
[2025-05-03T04:58:41.029+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvp5bou6i9/requirements.txt (line 1)) (2023.4)
[2025-05-03T04:58:41.104+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (3.0.3)
[2025-05-03T04:58:41.161+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (2.26.2)
[2025-05-03T04:58:41.212+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (4.0.12)
[2025-05-03T04:58:41.245+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (3.17.0)
[2025-05-03T04:58:41.274+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (1.2.14)
[2025-05-03T04:58:41.281+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (0.43b0)
[2025-05-03T04:58:41.316+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvp5bou6i9/requirements.txt (line 1)) (1.16.0)
[2025-05-03T04:58:41.334+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (3.3.2)
[2025-05-03T04:58:41.335+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (3.6)
[2025-05-03T04:58:41.336+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (2023.11.17)
[2025-05-03T04:58:41.402+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (1.16.0)
[2025-05-03T04:58:41.407+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (5.0.2)
[2025-05-03T04:58:41.420+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (0.3.0)
[2025-05-03T04:58:41.421+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (4.9)
[2025-05-03T04:58:41.452+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvp5bou6i9/requirements.txt (line 3)) (0.5.1)
[2025-05-03T04:58:41.486+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-03T04:58:41.515+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 14.1 MB/s eta 0:00:00
[2025-05-03T04:58:43.357+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-03T04:58:43.539+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-03T04:58:43.648+0000] {process_utils.py:190} INFO - 
[2025-05-03T04:58:43.648+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-03T04:58:43.649+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-03T04:58:43.789+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvp5bou6i9/bin/python /tmp/venv-call5b0yt82b/script.py /tmp/venv-call5b0yt82b/script.in /tmp/venv-call5b0yt82b/script.out /tmp/venv-call5b0yt82b/string_args.txt /tmp/venv-call5b0yt82b/termination.log
[2025-05-03T04:58:43.796+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T04:58:44.378+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-03T04:58:45.865+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:45.864+0000[0m] {[34mscript.py:[0m52} INFO[0m - Starting to read training and testing datasets from S3/Minio[0m
[2025-05-03T04:58:45.875+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:45.874+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T04:58:45.931+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:45.930+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T04:58:45.976+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:45.976+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T04:58:46.127+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.126+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T04:58:46.167+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.167+0000[0m] {[34mscript.py:[0m58} INFO[0m - Training and testing datasets loaded successfully from S3/Minio[0m
[2025-05-03T04:58:46.168+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.167+0000[0m] {[34mscript.py:[0m59} INFO[0m - Training set shape: (3577, 16), Testing set shape: (1533, 16)[0m
[2025-05-03T04:58:46.169+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.167+0000[0m] {[34mscript.py:[0m64} INFO[0m - Initializing the StandardScaler[0m
[2025-05-03T04:58:46.176+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.175+0000[0m] {[34mscript.py:[0m81} INFO[0m - Data normalization completed successfully using StandardScaler[0m
[2025-05-03T04:58:46.176+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.176+0000[0m] {[34mscript.py:[0m85} INFO[0m - Scaler mean: [4.32504333e+01 9.61699748e-02 5.39558289e-02 1.05845801e+02
[2025-05-03T04:58:46.177+0000] {process_utils.py:190} INFO -  3.04166620e+01]... (showing first 5 elements)[0m
[2025-05-03T04:58:46.177+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.176+0000[0m] {[34mscript.py:[0m86} INFO[0m - Scaler scale: [22.48993273  0.2948242   0.22593051 44.5820797  10.73996514]... (showing first 5 elements)[0m
[2025-05-03T04:58:46.180+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.180+0000[0m] {[34mscript.py:[0m105} INFO[0m - Scaled data successfully converted to DataFrame[0m
[2025-05-03T04:58:46.180+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.180+0000[0m] {[34mscript.py:[0m110} INFO[0m - Starting to save scaled training and testing datasets to S3/Minio[0m
[2025-05-03T04:58:46.189+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.188+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T04:58:46.240+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.239+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T04:58:46.314+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.313+0000[0m] {[34mscript.py:[0m115} INFO[0m - Scaled training data saved successfully to s3://data/train/stroke_data_X_train_scaled.csv[0m
[2025-05-03T04:58:46.321+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.321+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T04:58:46.373+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.373+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T04:58:46.411+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.410+0000[0m] {[34mscript.py:[0m118} INFO[0m - Scaled testing data saved successfully to s3://data/test/stroke_data_X_test_scaled.csv[0m
[2025-05-03T04:58:46.412+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.411+0000[0m] {[34mscript.py:[0m123} INFO[0m - Updating dataset information with scaler details[0m
[2025-05-03T04:58:46.418+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.418+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T04:58:46.573+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.573+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T04:58:46.585+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.584+0000[0m] {[34mscript.py:[0m134} INFO[0m - Existing dataset information loaded from S3/Minio[0m
[2025-05-03T04:58:46.591+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.591+0000[0m] {[34mscript.py:[0m153} INFO[0m - Dataset information updated successfully in S3/Minio with scaler details[0m
[2025-05-03T04:58:46.592+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.591+0000[0m] {[34mscript.py:[0m159} INFO[0m - Logging scaler details and dataset info to MLflow[0m
[2025-05-03T04:58:46.917+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.917+0000[0m] {[34mscript.py:[0m201} INFO[0m - Scaler details and dataset info logged to MLflow successfully in run: normalize_data_20250503_045846[0m
[2025-05-03T04:58:46.949+0000] {process_utils.py:190} INFO - 2025/05/03 04:58:46 INFO mlflow.tracking._tracking_service.client: 🏃 View run normalize_data_20250503_045846 at: http://mlflow:5000/#/experiments/1/runs/5afe9f0369b24b3fb5ca69241b74a053.
[2025-05-03T04:58:46.950+0000] {process_utils.py:190} INFO - 2025/05/03 04:58:46 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-03T04:58:46.969+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:46.969+0000[0m] {[34mscript.py:[0m203} INFO[0m - Data normalization process completed successfully[0m
[2025-05-03T04:58:47.382+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-03T04:58:47.394+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=normalize_data, execution_date=20250502T000000, start_date=20250503T045838, end_date=20250503T045847
[2025-05-03T04:58:47.422+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-03T04:58:47.438+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T13:44:38.745+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T13:44:38.753+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T13:44:38.754+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-03T13:44:38.767+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): normalize_data> on 2025-05-02 00:00:00+00:00
[2025-05-03T13:44:38.773+0000] {standard_task_runner.py:60} INFO - Started process 865 to run task
[2025-05-03T13:44:38.776+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'normalize_data', 'scheduled__2025-05-02T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmpb8gui916']
[2025-05-03T13:44:38.778+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask normalize_data
[2025-05-03T13:44:38.823+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-02T00:00:00+00:00 [running]> on host 8fb4c1e7dfa6
[2025-05-03T13:44:38.880+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='normalize_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-02T00:00:00+00:00'
[2025-05-03T13:44:38.881+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvffzjmc3t --system-site-packages --python=python
[2025-05-03T13:44:38.888+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T13:44:39.542+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 340ms
[2025-05-03T13:44:39.543+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvffzjmc3t, clear=False, no_vcs_ignore=False, global=True)
[2025-05-03T13:44:39.544+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmp0ed0j7m3)
[2025-05-03T13:44:39.544+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-03T13:44:39.544+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-03T13:44:39.577+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvffzjmc3t/bin/pip install -r /tmp/venvffzjmc3t/requirements.txt
[2025-05-03T13:44:39.586+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T13:44:40.212+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-03T13:44:40.444+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venvffzjmc3t/requirements.txt (line 1))
[2025-05-03T13:44:40.488+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-03T13:44:40.490+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvffzjmc3t/requirements.txt (line 2)) (1.37.38)
[2025-05-03T13:44:40.491+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvffzjmc3t/requirements.txt (line 3)) (2.17.2)
[2025-05-03T13:44:40.492+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvffzjmc3t/requirements.txt (line 4)) (1.3.2)
[2025-05-03T13:44:40.528+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvffzjmc3t/requirements.txt (line 1)) (1.37.38)
[2025-05-03T13:44:40.530+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvffzjmc3t/requirements.txt (line 1)) (1.24.4)
[2025-05-03T13:44:40.530+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvffzjmc3t/requirements.txt (line 1)) (23.2)
[2025-05-03T13:44:40.531+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvffzjmc3t/requirements.txt (line 1)) (2.0.3)
[2025-05-03T13:44:40.532+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvffzjmc3t/requirements.txt (line 1)) (14.0.2)
[2025-05-03T13:44:40.532+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvffzjmc3t/requirements.txt (line 1)) (4.9.0)
[2025-05-03T13:44:40.538+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venvffzjmc3t/requirements.txt (line 2)) (0.10.0)
[2025-05-03T13:44:40.539+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venvffzjmc3t/requirements.txt (line 2)) (0.11.5)
[2025-05-03T13:44:40.578+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (2.17.2)
[2025-05-03T13:44:40.579+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (2.2.5)
[2025-05-03T13:44:40.579+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (1.13.1)
[2025-05-03T13:44:40.580+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (7.0.0)
[2025-05-03T13:44:40.580+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (3.4.3)
[2025-05-03T13:44:40.581+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (3.5.2)
[2025-05-03T13:44:40.581+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (3.7.5)
[2025-05-03T13:44:40.582+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (1.10.1)
[2025-05-03T13:44:40.583+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (1.4.51)
[2025-05-03T13:44:40.584+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (3.1.3)
[2025-05-03T13:44:40.585+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (21.2.0)
[2025-05-03T13:44:40.621+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (5.3.2)
[2025-05-03T13:44:40.622+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (8.1.7)
[2025-05-03T13:44:40.623+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (3.1.1)
[2025-05-03T13:44:40.624+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (0.51.0)
[2025-05-03T13:44:40.624+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (3.1.44)
[2025-05-03T13:44:40.625+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (6.11.0)
[2025-05-03T13:44:40.625+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (1.22.0)
[2025-05-03T13:44:40.626+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (1.22.0)
[2025-05-03T13:44:40.627+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (4.25.2)
[2025-05-03T13:44:40.627+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (6.0.1)
[2025-05-03T13:44:40.628+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (2.31.0)
[2025-05-03T13:44:40.631+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (0.4.4)
[2025-05-03T13:44:40.652+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn->-r /tmp/venvffzjmc3t/requirements.txt (line 4)) (1.4.2)
[2025-05-03T13:44:40.653+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn->-r /tmp/venvffzjmc3t/requirements.txt (line 4)) (3.5.0)
[2025-05-03T13:44:40.659+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (1.3.0)
[2025-05-03T13:44:40.663+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (5.13.0)
[2025-05-03T13:44:40.667+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvffzjmc3t/requirements.txt (line 1)) (2.8.2)
[2025-05-03T13:44:40.670+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvffzjmc3t/requirements.txt (line 1)) (1.26.18)
[2025-05-03T13:44:40.677+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (2.2.3)
[2025-05-03T13:44:40.680+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (2.1.2)
[2025-05-03T13:44:40.705+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (3.2.6)
[2025-05-03T13:44:40.706+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (3.2.0)
[2025-05-03T13:44:40.713+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (2.1.3)
[2025-05-03T13:44:40.733+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (1.1.1)
[2025-05-03T13:44:40.734+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (0.12.1)
[2025-05-03T13:44:40.734+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (4.57.0)
[2025-05-03T13:44:40.735+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (1.4.7)
[2025-05-03T13:44:40.735+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (10.4.0)
[2025-05-03T13:44:40.736+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (3.1.1)
[2025-05-03T13:44:40.808+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvffzjmc3t/requirements.txt (line 1)) (2023.3.post1)
[2025-05-03T13:44:40.809+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvffzjmc3t/requirements.txt (line 1)) (2023.4)
[2025-05-03T13:44:40.890+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (3.0.3)
[2025-05-03T13:44:40.944+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (2.26.2)
[2025-05-03T13:44:40.988+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (4.0.12)
[2025-05-03T13:44:41.023+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (3.17.0)
[2025-05-03T13:44:41.058+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (1.2.14)
[2025-05-03T13:44:41.065+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (0.43b0)
[2025-05-03T13:44:41.099+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvffzjmc3t/requirements.txt (line 1)) (1.16.0)
[2025-05-03T13:44:41.118+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (3.3.2)
[2025-05-03T13:44:41.119+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (3.6)
[2025-05-03T13:44:41.120+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (2023.11.17)
[2025-05-03T13:44:41.193+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (1.16.0)
[2025-05-03T13:44:41.199+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (5.0.2)
[2025-05-03T13:44:41.214+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (0.3.0)
[2025-05-03T13:44:41.215+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (4.9)
[2025-05-03T13:44:41.255+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvffzjmc3t/requirements.txt (line 3)) (0.5.1)
[2025-05-03T13:44:41.301+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-03T13:44:41.319+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 25.1 MB/s eta 0:00:00
[2025-05-03T13:44:43.384+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-03T13:44:43.599+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-03T13:44:43.691+0000] {process_utils.py:190} INFO - 
[2025-05-03T13:44:43.692+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-03T13:44:43.692+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-03T13:44:43.917+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvffzjmc3t/bin/python /tmp/venv-call9bczwxth/script.py /tmp/venv-call9bczwxth/script.in /tmp/venv-call9bczwxth/script.out /tmp/venv-call9bczwxth/string_args.txt /tmp/venv-call9bczwxth/termination.log
[2025-05-03T13:44:43.927+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T13:44:44.679+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-03T13:44:46.169+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.168+0000[0m] {[34mscript.py:[0m52} INFO[0m - Starting to read training and testing datasets from S3/Minio[0m
[2025-05-03T13:44:46.179+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.179+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T13:44:46.237+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.236+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T13:44:46.286+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.285+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T13:44:46.483+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.482+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T13:44:46.520+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.519+0000[0m] {[34mscript.py:[0m58} INFO[0m - Training and testing datasets loaded successfully from S3/Minio[0m
[2025-05-03T13:44:46.520+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.520+0000[0m] {[34mscript.py:[0m59} INFO[0m - Training set shape: (3577, 16), Testing set shape: (1533, 16)[0m
[2025-05-03T13:44:46.521+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.520+0000[0m] {[34mscript.py:[0m64} INFO[0m - Initializing the StandardScaler[0m
[2025-05-03T13:44:46.528+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.528+0000[0m] {[34mscript.py:[0m81} INFO[0m - Data normalization completed successfully using StandardScaler[0m
[2025-05-03T13:44:46.529+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.528+0000[0m] {[34mscript.py:[0m85} INFO[0m - Scaler mean: [4.32504333e+01 9.61699748e-02 5.39558289e-02 1.05845801e+02
[2025-05-03T13:44:46.529+0000] {process_utils.py:190} INFO -  3.04166620e+01]... (showing first 5 elements)[0m
[2025-05-03T13:44:46.529+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.528+0000[0m] {[34mscript.py:[0m86} INFO[0m - Scaler scale: [22.48993273  0.2948242   0.22593051 44.5820797  10.73996514]... (showing first 5 elements)[0m
[2025-05-03T13:44:46.533+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.533+0000[0m] {[34mscript.py:[0m105} INFO[0m - Scaled data successfully converted to DataFrame[0m
[2025-05-03T13:44:46.534+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.533+0000[0m] {[34mscript.py:[0m110} INFO[0m - Starting to save scaled training and testing datasets to S3/Minio[0m
[2025-05-03T13:44:46.542+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.542+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T13:44:46.602+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.602+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T13:44:46.674+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.674+0000[0m] {[34mscript.py:[0m115} INFO[0m - Scaled training data saved successfully to s3://data/train/stroke_data_X_train_scaled.csv[0m
[2025-05-03T13:44:46.683+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.682+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T13:44:46.738+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.738+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T13:44:46.776+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.775+0000[0m] {[34mscript.py:[0m118} INFO[0m - Scaled testing data saved successfully to s3://data/test/stroke_data_X_test_scaled.csv[0m
[2025-05-03T13:44:46.777+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.776+0000[0m] {[34mscript.py:[0m123} INFO[0m - Updating dataset information with scaler details[0m
[2025-05-03T13:44:46.784+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.784+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T13:44:46.957+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.956+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T13:44:46.971+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.971+0000[0m] {[34mscript.py:[0m134} INFO[0m - Existing dataset information loaded from S3/Minio[0m
[2025-05-03T13:44:46.978+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.978+0000[0m] {[34mscript.py:[0m153} INFO[0m - Dataset information updated successfully in S3/Minio with scaler details[0m
[2025-05-03T13:44:46.979+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:46.978+0000[0m] {[34mscript.py:[0m159} INFO[0m - Logging scaler details and dataset info to MLflow[0m
[2025-05-03T13:44:47.354+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:47.353+0000[0m] {[34mscript.py:[0m201} INFO[0m - Scaler details and dataset info logged to MLflow successfully in run: normalize_data_20250503_134447[0m
[2025-05-03T13:44:47.379+0000] {process_utils.py:190} INFO - 2025/05/03 13:44:47 INFO mlflow.tracking._tracking_service.client: 🏃 View run normalize_data_20250503_134447 at: http://mlflow:5000/#/experiments/1/runs/400f0980ba4c4bebae1c70412cf6f816.
[2025-05-03T13:44:47.380+0000] {process_utils.py:190} INFO - 2025/05/03 13:44:47 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-03T13:44:47.402+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:47.401+0000[0m] {[34mscript.py:[0m203} INFO[0m - Data normalization process completed successfully[0m
[2025-05-03T13:44:47.827+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-03T13:44:47.837+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=normalize_data, execution_date=20250502T000000, start_date=20250503T134438, end_date=20250503T134447
[2025-05-03T13:44:47.876+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-03T13:44:47.896+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T18:02:36.599+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T18:02:36.609+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T18:02:36.610+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-03T18:02:36.624+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): normalize_data> on 2025-05-02 00:00:00+00:00
[2025-05-03T18:02:36.628+0000] {standard_task_runner.py:60} INFO - Started process 877 to run task
[2025-05-03T18:02:36.631+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'normalize_data', 'scheduled__2025-05-02T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmp74e5wp38']
[2025-05-03T18:02:36.634+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask normalize_data
[2025-05-03T18:02:36.682+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.normalize_data scheduled__2025-05-02T00:00:00+00:00 [running]> on host 2042e9a26c53
[2025-05-03T18:02:36.749+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='normalize_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-02T00:00:00+00:00'
[2025-05-03T18:02:36.752+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venva3bp6425 --system-site-packages --python=python
[2025-05-03T18:02:36.759+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T18:02:37.313+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 289ms
[2025-05-03T18:02:37.314+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venva3bp6425, clear=False, no_vcs_ignore=False, global=True)
[2025-05-03T18:02:37.315+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmpi40zy8sr)
[2025-05-03T18:02:37.316+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-03T18:02:37.321+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-03T18:02:37.349+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venva3bp6425/bin/pip install -r /tmp/venva3bp6425/requirements.txt
[2025-05-03T18:02:37.356+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T18:02:37.954+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-03T18:02:38.161+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venva3bp6425/requirements.txt (line 1))
[2025-05-03T18:02:38.217+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-03T18:02:38.220+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venva3bp6425/requirements.txt (line 2)) (1.37.38)
[2025-05-03T18:02:38.220+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venva3bp6425/requirements.txt (line 3)) (2.17.2)
[2025-05-03T18:02:38.221+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venva3bp6425/requirements.txt (line 4)) (1.3.2)
[2025-05-03T18:02:38.254+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venva3bp6425/requirements.txt (line 1)) (1.37.38)
[2025-05-03T18:02:38.255+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venva3bp6425/requirements.txt (line 1)) (1.24.4)
[2025-05-03T18:02:38.256+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venva3bp6425/requirements.txt (line 1)) (23.2)
[2025-05-03T18:02:38.257+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venva3bp6425/requirements.txt (line 1)) (2.0.3)
[2025-05-03T18:02:38.257+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venva3bp6425/requirements.txt (line 1)) (14.0.2)
[2025-05-03T18:02:38.258+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venva3bp6425/requirements.txt (line 1)) (4.9.0)
[2025-05-03T18:02:38.262+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venva3bp6425/requirements.txt (line 2)) (0.10.0)
[2025-05-03T18:02:38.263+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venva3bp6425/requirements.txt (line 2)) (0.11.5)
[2025-05-03T18:02:38.302+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (2.17.2)
[2025-05-03T18:02:38.303+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (2.2.5)
[2025-05-03T18:02:38.304+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (1.13.1)
[2025-05-03T18:02:38.304+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (7.0.0)
[2025-05-03T18:02:38.305+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (3.4.3)
[2025-05-03T18:02:38.306+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (3.5.2)
[2025-05-03T18:02:38.307+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (3.7.5)
[2025-05-03T18:02:38.307+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (1.10.1)
[2025-05-03T18:02:38.308+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (1.4.51)
[2025-05-03T18:02:38.310+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (3.1.3)
[2025-05-03T18:02:38.310+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (21.2.0)
[2025-05-03T18:02:38.342+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (5.3.2)
[2025-05-03T18:02:38.343+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (8.1.7)
[2025-05-03T18:02:38.344+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (3.1.1)
[2025-05-03T18:02:38.345+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (0.51.0)
[2025-05-03T18:02:38.345+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (3.1.44)
[2025-05-03T18:02:38.346+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (6.11.0)
[2025-05-03T18:02:38.346+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (1.22.0)
[2025-05-03T18:02:38.347+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (1.22.0)
[2025-05-03T18:02:38.347+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (4.25.2)
[2025-05-03T18:02:38.348+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (6.0.1)
[2025-05-03T18:02:38.349+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (2.31.0)
[2025-05-03T18:02:38.349+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (0.4.4)
[2025-05-03T18:02:38.371+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn->-r /tmp/venva3bp6425/requirements.txt (line 4)) (1.4.2)
[2025-05-03T18:02:38.373+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn->-r /tmp/venva3bp6425/requirements.txt (line 4)) (3.5.0)
[2025-05-03T18:02:38.378+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (1.3.0)
[2025-05-03T18:02:38.379+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (5.13.0)
[2025-05-03T18:02:38.384+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venva3bp6425/requirements.txt (line 1)) (2.8.2)
[2025-05-03T18:02:38.385+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venva3bp6425/requirements.txt (line 1)) (1.26.18)
[2025-05-03T18:02:38.397+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (2.2.3)
[2025-05-03T18:02:38.398+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (2.1.2)
[2025-05-03T18:02:38.423+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (3.2.6)
[2025-05-03T18:02:38.424+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (3.2.0)
[2025-05-03T18:02:38.431+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (2.1.3)
[2025-05-03T18:02:38.452+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (1.1.1)
[2025-05-03T18:02:38.453+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (0.12.1)
[2025-05-03T18:02:38.454+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (4.57.0)
[2025-05-03T18:02:38.454+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (1.4.7)
[2025-05-03T18:02:38.455+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (10.4.0)
[2025-05-03T18:02:38.455+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (3.1.1)
[2025-05-03T18:02:38.521+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venva3bp6425/requirements.txt (line 1)) (2023.3.post1)
[2025-05-03T18:02:38.522+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venva3bp6425/requirements.txt (line 1)) (2023.4)
[2025-05-03T18:02:38.596+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (3.0.3)
[2025-05-03T18:02:38.648+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (2.26.2)
[2025-05-03T18:02:38.690+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (4.0.12)
[2025-05-03T18:02:38.723+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (3.17.0)
[2025-05-03T18:02:38.750+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (1.2.14)
[2025-05-03T18:02:38.756+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (0.43b0)
[2025-05-03T18:02:38.789+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venva3bp6425/requirements.txt (line 1)) (1.16.0)
[2025-05-03T18:02:38.805+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (3.3.2)
[2025-05-03T18:02:38.806+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (3.6)
[2025-05-03T18:02:38.807+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (2023.11.17)
[2025-05-03T18:02:38.864+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (1.16.0)
[2025-05-03T18:02:38.870+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (5.0.2)
[2025-05-03T18:02:38.883+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (0.3.0)
[2025-05-03T18:02:38.884+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (4.9)
[2025-05-03T18:02:38.917+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venva3bp6425/requirements.txt (line 3)) (0.5.1)
[2025-05-03T18:02:38.953+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-03T18:02:38.977+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 17.7 MB/s eta 0:00:00
[2025-05-03T18:02:40.767+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-03T18:02:40.952+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-03T18:02:41.037+0000] {process_utils.py:190} INFO - 
[2025-05-03T18:02:41.038+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-03T18:02:41.039+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-03T18:02:41.155+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venva3bp6425/bin/python /tmp/venv-callxljjs9px/script.py /tmp/venv-callxljjs9px/script.in /tmp/venv-callxljjs9px/script.out /tmp/venv-callxljjs9px/string_args.txt /tmp/venv-callxljjs9px/termination.log
[2025-05-03T18:02:41.163+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T18:02:41.701+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-03T18:02:43.091+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.090+0000[0m] {[34mscript.py:[0m52} INFO[0m - Starting to read training and testing datasets from S3/Minio[0m
[2025-05-03T18:02:43.099+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.098+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T18:02:43.160+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.159+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T18:02:43.202+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.202+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T18:02:43.325+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.324+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T18:02:43.350+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.350+0000[0m] {[34mscript.py:[0m58} INFO[0m - Training and testing datasets loaded successfully from S3/Minio[0m
[2025-05-03T18:02:43.351+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.350+0000[0m] {[34mscript.py:[0m59} INFO[0m - Training set shape: (3577, 16), Testing set shape: (1533, 16)[0m
[2025-05-03T18:02:43.351+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.350+0000[0m] {[34mscript.py:[0m64} INFO[0m - Initializing the StandardScaler[0m
[2025-05-03T18:02:43.356+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.356+0000[0m] {[34mscript.py:[0m81} INFO[0m - Data normalization completed successfully using StandardScaler[0m
[2025-05-03T18:02:43.357+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.356+0000[0m] {[34mscript.py:[0m85} INFO[0m - Scaler mean: [4.32504333e+01 9.61699748e-02 5.39558289e-02 1.05845801e+02
[2025-05-03T18:02:43.357+0000] {process_utils.py:190} INFO -  3.04166620e+01]... (showing first 5 elements)[0m
[2025-05-03T18:02:43.358+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.357+0000[0m] {[34mscript.py:[0m86} INFO[0m - Scaler scale: [22.48993273  0.2948242   0.22593051 44.5820797  10.73996514]... (showing first 5 elements)[0m
[2025-05-03T18:02:43.360+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.360+0000[0m] {[34mscript.py:[0m105} INFO[0m - Scaled data successfully converted to DataFrame[0m
[2025-05-03T18:02:43.361+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.360+0000[0m] {[34mscript.py:[0m110} INFO[0m - Starting to save scaled training and testing datasets to S3/Minio[0m
[2025-05-03T18:02:43.368+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.367+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T18:02:43.410+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.409+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T18:02:43.494+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.494+0000[0m] {[34mscript.py:[0m115} INFO[0m - Scaled training data saved successfully to s3://data/train/stroke_data_X_train_scaled.csv[0m
[2025-05-03T18:02:43.501+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.501+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T18:02:43.549+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.548+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T18:02:43.579+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.579+0000[0m] {[34mscript.py:[0m118} INFO[0m - Scaled testing data saved successfully to s3://data/test/stroke_data_X_test_scaled.csv[0m
[2025-05-03T18:02:43.580+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.579+0000[0m] {[34mscript.py:[0m123} INFO[0m - Updating dataset information with scaler details[0m
[2025-05-03T18:02:43.586+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.585+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T18:02:43.735+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.735+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T18:02:43.746+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.746+0000[0m] {[34mscript.py:[0m134} INFO[0m - Existing dataset information loaded from S3/Minio[0m
[2025-05-03T18:02:43.753+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.753+0000[0m] {[34mscript.py:[0m153} INFO[0m - Dataset information updated successfully in S3/Minio with scaler details[0m
[2025-05-03T18:02:43.753+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:43.753+0000[0m] {[34mscript.py:[0m159} INFO[0m - Logging scaler details and dataset info to MLflow[0m
[2025-05-03T18:02:44.080+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:44.080+0000[0m] {[34mscript.py:[0m201} INFO[0m - Scaler details and dataset info logged to MLflow successfully in run: normalize_data_20250503_180243[0m
[2025-05-03T18:02:44.105+0000] {process_utils.py:190} INFO - 2025/05/03 18:02:44 INFO mlflow.tracking._tracking_service.client: 🏃 View run normalize_data_20250503_180243 at: http://mlflow:5000/#/experiments/1/runs/6fa5047304f541c3817e12d83f35f0d2.
[2025-05-03T18:02:44.106+0000] {process_utils.py:190} INFO - 2025/05/03 18:02:44 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-03T18:02:44.125+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:44.124+0000[0m] {[34mscript.py:[0m203} INFO[0m - Data normalization process completed successfully[0m
[2025-05-03T18:02:44.494+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-03T18:02:44.506+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=normalize_data, execution_date=20250502T000000, start_date=20250503T180236, end_date=20250503T180244
[2025-05-03T18:02:44.555+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-03T18:02:44.577+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
